version: '3'
services:
    php:
        image: php-custom
        links:
           - mariadb
        expose:
           - 9000
        networks:
          - backend
        volumes:
           - ./DocumentRoot:/var/www/html
        deploy:
          replicas: 2
          update_config:
           parallelism: 2
           delay: 10s

    apache:
        image: apache-custom
        ports:
          - 6666:80
        volumes:
            - ./DocumentRoot:/var/www/html
            - ./apache/docker.apache.conf:/usr/local/apache2/conf.d/docker.apache.conf
        networks:
            - frontend
            - backend
        links: 
          - php
        deploy:
          replicas: 2
          update_config:
           parallelism: 2
           delay: 10s


    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'
        networks:
          - backend
        deploy:
          replicas: 1
          update_config:
           parallelism: 2
           delay: 10s

volumes:
    mariadb:

networks:
     frontend:
         driver: overlay
     backend:
         driver: overlay 
